// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvx_Nq7UBrmhGqSO0a8BwATOqu4URHTnA',
    appId: '1:361905360400:web:44dff46e0f1f52b98dc495',
    messagingSenderId: '361905360400',
    projectId: 'bac-monitor-9e9a4',
    authDomain: 'bac-monitor-9e9a4.firebaseapp.com',
    databaseURL: 'https://bac-monitor-9e9a4-default-rtdb.firebaseio.com',
    storageBucket: 'bac-monitor-9e9a4.firebasestorage.app',
    measurementId: 'G-NK37TX25GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFb4eWiv4mj2Ovwgjlv1ARqYFIJMk3Dyw',
    appId: '1:361905360400:android:5077d0a0574925518dc495',
    messagingSenderId: '361905360400',
    projectId: 'bac-monitor-9e9a4',
    databaseURL: 'https://bac-monitor-9e9a4-default-rtdb.firebaseio.com',
    storageBucket: 'bac-monitor-9e9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD46wRnQd6PMVd2cmmqglpKVm1AkCmMjo',
    appId: '1:361905360400:ios:d04dd5b107b32de88dc495',
    messagingSenderId: '361905360400',
    projectId: 'bac-monitor-9e9a4',
    databaseURL: 'https://bac-monitor-9e9a4-default-rtdb.firebaseio.com',
    storageBucket: 'bac-monitor-9e9a4.firebasestorage.app',
    iosClientId: '361905360400-qoa21l8s1b41ptrs9l2htokp7sbd3rjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD46wRnQd6PMVd2cmmqglpKVm1AkCmMjo',
    appId: '1:361905360400:ios:d04dd5b107b32de88dc495',
    messagingSenderId: '361905360400',
    projectId: 'bac-monitor-9e9a4',
    databaseURL: 'https://bac-monitor-9e9a4-default-rtdb.firebaseio.com',
    storageBucket: 'bac-monitor-9e9a4.firebasestorage.app',
    iosClientId: '361905360400-qoa21l8s1b41ptrs9l2htokp7sbd3rjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvx_Nq7UBrmhGqSO0a8BwATOqu4URHTnA',
    appId: '1:361905360400:web:68d6750b0d687a6f8dc495',
    messagingSenderId: '361905360400',
    projectId: 'bac-monitor-9e9a4',
    authDomain: 'bac-monitor-9e9a4.firebaseapp.com',
    databaseURL: 'https://bac-monitor-9e9a4-default-rtdb.firebaseio.com',
    storageBucket: 'bac-monitor-9e9a4.firebasestorage.app',
    measurementId: 'G-PNRPMVDC6K',
  );

}